name: check

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    schedule:
        - cron: "0 0 * * 0"

jobs:
    cov:
        uses: ./.github/workflows/.hatch-run.yml
        with:
            job-name: "python-{0}"
            hatch-run: "cov"
    lint:
        uses: ./.github/workflows/.hatch-run.yml
        with:
            job-name: "lint"
            hatch-run: "lint"
    matrix:
        uses: ./.github/workflows/.hatch-run.yml
        with:
            job-name: "python-{0}-{1}"
            hatch-run: "test"
            runs-on-array: '["ubuntu-latest", "macos-latest", "windows-latest"]'
            python-version-array: '["3.10", "3.11"]'
    docs:
        uses: ./.github/workflows/.hatch-run.yml
        with:
            job-name: "docs"
            hatch-run: "docs-build"
