name: publish-pypi

on:
    release:
        types: [published]

jobs:
    publish-pypi:
        uses: ./.github/workflows/.hatch-run.yml
        with:
            job-name: "publish-pypi"
            hatch-run: "publish-pypi"
        secrets:
            pypi-username: ${{ secrets.PYPI_USERNAME }}
            pypi-password: ${{ secrets.PYPI_PASSWORD }}
